### ISSUE TITLE
想問怎麼沒有看到書上的程式包

### ISSUE THREAD

**Issue by houhouryan** [arleigh418/arleigh418#1]
想問怎麼沒有看到書上的程式包

**Comment by arleigh418** [comment]
Hi~您好，這個儲存庫只是我的個人介紹頁面哦，跟書有關的程式包在這裡:
1. [書中主要程式](https://github.com/arleigh418/python-and-Taiwan-stock-market)
2. [看完後的進階補充](https://github.com/arleigh418/python-and-Taiwan-stock-market-Advanced)
3. [加密的單元會用到的工具包](https://github.com/arleigh418/AES-Encryption)

以上，感謝您提出問題~希望有幫助到你。
