### ISSUE TITLE
不好意思

### ISSUE THREAD

**Issue by houhouryan** [arleigh418/arleigh418#2]
我在按照書的步驟時，有一個地方有問題，在2-17的地方安裝那些套件時，cmd打出來的時候顯示沒有
![image](https://user-images.githubusercontent.com/91065933/134008348-19268096-8986-46dc-b52f-65c4f4e62619.png)

**Comment by arleigh418** [comment]
問題出在虛擬環境的某個config檔消失，有可能發生於誤刪，或者跟電腦環境有關係，因此我們可以先嘗試幾個步驟看看:
1. 退出虛擬環境後，嘗試原本機的pip是否可以install? (直接打開cmd，輸入pip install requests)

2. 若1.可以，那我的建議是先砍掉位於D\vscode\Microsoft VS CODE路徑裡的env，我不確定env裝在這個路徑會不會有影響，建議在D開一個專門的資料夾，例如D:/Trading或者是D:/Test都可以，然後再至該路徑下重新創建嘗試。

3. 若是1.不行，我建議嘗試至控制台將python全部砍乾淨並重新下載，盡量先不要使用客製安裝，直接點選Install Now，並確保下方Add Python x.x to Path勾起，然後一樣開D:/Trading或者是D:/Test都可以，至該路徑下重新創建虛擬環境嘗試

**Comment by arleigh418** [comment]
對了，為了讓所有讀者都能看到跟書籍有關的問題，可能要麻煩您至下面連結發出issue，在這裡可能很多人看不到，感謝!
[https://github.com/arleigh418/python-and-Taiwan-stock-market](https://github.com/arleigh418/python-and-Taiwan-stock-market)
