### ISSUE TITLE
找不到模組

### ISSUE THREAD

**Issue by RAY0617** [arleigh418/arleigh418#3]
https://user-images.githubusercontent.com/93468969/139575733-8a8dac52-8466-41a0-8b8c-586fcc130968.png
想請問為什麼找不到此模組
https://user-images.githubusercontent.com/93468969/139575796-4ee843f2-75f9-4bc4-8ad3-0499eb4c007a.png

**Comment by arleigh418** [comment]
Hi 您好，很高興您提問。
您的路徑 D:\test\hou\程式 裡面有utility_f.py這支程式嗎，如果沒有，您需要將那支程式丟到 D:\test\hou\程式 目錄裡。

如果有，此錯誤仍存在，那您可以嘗試:
1.將中文資料夾換成英文(e.g. 程式 -> code)
2.若您是用編譯器執行(目測是spyder?)，他的程式執行的路徑邏輯可能有它自己的規範，嘗試加入這一行在程式裡 (假設您已經將程式兩個中文字換成code):
`import sys
sys.path.append(r'D:\test\hou\code')`

另外題外話一下，希望能讓讀者看到大家所提出的問題，避免重複討論，希望您可以在專為此書開設的Github page中提問，在[這裡](https://github.com/arleigh418/python-and-Taiwan-stock-market)。

**Comment by RAY0617** [comment]
https://user-images.githubusercontent.com/93468969/139584970-04570bcc-a2e1-4318-b50e-0d5b2b9b57f6.png
https://user-images.githubusercontent.com/93468969/139585006-45564f13-473b-448a-bab3-ae0be1c3190a.png
想請問為什麼服務器不支持 SMTP AUTH 擴展。

**Comment by arleigh418** [comment]
我推測您的程式沒有打完整，可以再檢查看看，應是缺少以下，若設置了仍有問題再提出。
` server.starttls()`

另外還是希望您到這裡去提出問題: [https://github.com/arleigh418/python-and-Taiwan-stock-market](https://github.com/arleigh418/python-and-Taiwan-stock-market)

您現在發問的這裡是我的個人介紹，相當於我的經歷介紹。
