### ISSUE TITLE
No such file or directory: 'D:\\Trading Strategy_EX\\Chapter2\\stock_list.xlsx'

### ISSUE THREAD

**Issue by KentTseng** [arleigh418/arleigh418#4]
No such file or directory: 'D:\\Trading Strategy_EX\\Chapter2\\stock_list.xlsx'

**Comment by arleigh418** [comment]
您好，請您幫我看看該目錄底下是否真的有stock_list.xlsx這一個檔案。
如果沒有，可能要放進去;如果有，可能要請您描述一下您的程式執行方式。

另外請您至這裡開啟討論串哦，這裡才是跟書籍有關的討論串:
[https://github.com/arleigh418/python-and-Taiwan-stock-market](https://github.com/arleigh418/python-and-Taiwan-stock-market)

稍晚我就會close您的這個issue，在請您移去那裡做討論。
